server:
  port: 9527

spring:
  application:
    name: weldmes-cloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

zuul:
  routes:
    mydept.serviceId: weldmes-cloud
    mydept.path: /mydept/**
  ignored-services: "*"

info:
  app.name: gw-cloud
  company.name: www.gw.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$