server:
  port: 7001

spring:
  application:
    name: eureka-server

eureka:
  instance:
    #eureka服务端的实例名称
    hostname: eurekaserver
  client:
    serviceUrl:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false