server:
  port: 8001

#mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
#  type-aliases-package: com.gw.entities    # 所有Entity别名类所在包
#  mapper-locations:
#    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
#主键生成策略
# mybatis-plus 配置
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  config-location: classpath:mybatis/mybatis.cfg.xml
  mapper-locations: classpath:/mybatis/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.gw.entities
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    # 热加载mapper文件
    refresh: true
    db-config:
      db-type: mysql

spring:
  application:
    name: weldmes-cloud-provider
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/weldmesdb?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: 123456
          initialSize: 10
          minIdle: 10
          maxActive: 200
          # 打开PSCache，并且指定每个连接上PSCache的大小
          poolPreparedStatements: true
          maxPoolPreparedStatementPerConnectionSize: 20
            # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
          filters: stat,wall,slf4j
            # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
          connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
            #合并多个DruidDataSource的监控数据
          useGlobalDataSourceStat: true
        slave_1:
          url: jdbc:mysql://localhost:3306/weldmes-rtdata?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: 123456
          initialSize: 10
          minIdle: 10
          maxActive: 200
            # 打开PSCache，并且指定每个连接上PSCache的大小
          poolPreparedStatements: true
          maxPoolPreparedStatementPerConnectionSize: 20
            # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
          filters: stat,wall,slf4j
            # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
          connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
            #合并多个DruidDataSource的监控数据
          useGlobalDataSourceStat: true
#  mail:
#      default-encoding: utf-8
#      # 主机地址
#      host: smtp.qq.com
#      # 邮箱名
#      username: 492493640@qq.com
#      # 授权码
#      password: ionfpprfyvfqbdif


eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka/
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: weldmes-cloud-dept8001-hystrix
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: gw-cloud
  company.name: www.gw.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
