server:
  port: 9090
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    ds1: #数据源1
      type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
      driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
      url: jdbc:mysql://localhost:3306/weldmesdb?serverTimezone=UTC&useSSL=false        # 数据库名称
      username: root
      password: 123456
      initialSize: 10
      minIdle: 10
      maxActive: 200
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
    ds2: # 数据源2
      type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
      driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
      url: jdbc:mysql://localhost:3306/weldmes-rtdata?serverTimezone=UTC&useSSL=false        # 数据库名称
      username: root
      password: 123456
      initialSize: 10
      minIdle: 10
      maxActive: 200
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
#  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    # 配置连接池
#    jedis:
#      pool:
#        # 连接池最大连接数（使用负值表示没有限制）
#        max-active: 8
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1
#        # 连接池中的最大空闲连接
#        max-idle: 500
#        # 连接池中的最小空闲连接
#        min-idle: 0
#    # 连接超时时间（毫秒）
#    timeout: 2000
#    lettuce:
#      shutdown-timeout: 0
mqtt:
  host: localhost
  port: 1883
  clientId: das
  username: admin
  password: 123456
  connectionTimeout: 30000
  keepAliveInterval: 30000
  cleanSession: true
  automaticReconnect: true
nettyServer:
  port: 6666
# mybatis-plus 配置
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  config-location: classpath:/mybatis/mybatis.cfg.xml
  mapper-locations: classpath:/mybatis/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.shth.das.pojo
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    # 热加载mapper文件
    refresh: true
    db-config:
      db-type: mysql
