server:
  port: 9527

spring:
  application:
    name: weldmes-cloud-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: gateway-server
    appname: zuul-server
    hostname: gateway-server

zuul:
  routes:
    serviceId: weldmes-cloud
    path: /mydept/**
  ignored-services: "*"

#info:
#  app.name: gw-cloud
#  company.name: www.gw.com
#  build.artifactId: $project.artifactId$
#  build.version: $project.version$